app = "voice-inbox-api"
primary_region = "sjc"  # San Jose (or choose a region closer to your users)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "voice_inbox_data"
  destination = "/app/data" 